adding new ideas by registered & logged users
moraw9/IdeaBakers pull request #8
Opened 2021-04-30 10:09 UTC by moraw9

#tasks
- [ ] create layout for button
- [ ] create form for users
- [ ] validate input data 
- [ ] save data on firestore 
- [ ] reload data displayed on the page

2021-04-30 14:17 UTC, wozny1989 commented
@moraw9  Add space between `#` nad `task` i PR description - it should display much better (like header) 😄

2021-04-30 14:17 UTC, wozny1989 commented
Nice work with create list with tasks! 🚀

2021-04-30 14:36 UTC, wozny1989 commented on app/components/adding-new-idea/template.hbs
> +              <input type="text" class="form-control" id="title" placeholder="Enter project title" name="title" value={{this.changeset.title}} onchange={{fn this.setValue}} >
I'm not sure is `fn` helper is necessary when we call function `this.setValue` without properties. Try do this, and give me a feedback if it still work:
```suggestion
              <input type="text" class="form-control" id="title" placeholder="Enter project title" name="title" value={{this.changeset.title}} onchange={{this.setValue}} >
```

2021-05-02 15:26 UTC, moraw9 commented on app/components/adding-new-idea/template.hbs
> +              <input type="text" class="form-control" id="title" placeholder="Enter project title" name="title" value={{this.changeset.title}} onchange={{fn this.setValue}} >
Yes, it works without 'fn', I corrected it.

2021-05-02 17:05 UTC, wozny1989 commented on app/components/adding-new-idea/template.hbs
> +              <input type="text" class="form-control" id="title" placeholder="Enter project title" name="title" value={{this.changeset.title}} onchange={{fn this.setValue}} >
Cool!

2021-05-13 12:26 UTC, wozny1989 requested changes

2021-05-13 12:26 UTC, wozny1989 commented on app/helpers/getExcerpt.js
> +  // console.log('string', string);
✂️

2021-05-13 16:19 UTC, merged